### ISSUE TITLE
Wails fails to serve the app because there are missing files

### ISSUE THREAD

**Issue by neilco** [nkoporec/ginker#2]
### Summary: 

Wails fails to serve the app because there are missing files. 

### Steps to Reproduce:

- Following the steps from the [Building section](https://github.com/nkoporec/ginker#building) in the README.

### Environment:

- macOS 11.3.1 (Big Sur)
- Go 1.16.4 (installed from official package)
- Wails 1.16.3

### Expected Outcome:

- Wails run successfully. 

### Actual Outcome:

- Wails exits following output:

```shell
Wails v1.16.3 - Serving Application

⢿ Ensuring Dependencies are up to date...main.go:18:12: pattern frontend/dist/app.css: no matching files found


✗ Ensuring Dependencies are up to date...
Error: exit status 1
```

### Notes

It looks like you’re missing an instruction to run `npm run build` **_before_** running `npm run serve`.

**Comment by nkoporec** [comment]
Added to the readme, thanks!
